package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *JsonPerson) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "userName":
			z.Username, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "favouriteNumber":
			z.FavoriteNumber, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "FavoriteNumber")
				return
			}
		case "interests":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Interests")
				return
			}
			if cap(z.Interests) >= int(zb0002) {
				z.Interests = (z.Interests)[:zb0002]
			} else {
				z.Interests = make([]string, zb0002)
			}
			for za0001 := range z.Interests {
				z.Interests[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Interests", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *JsonPerson) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "userName"
	err = en.Append(0x83, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Username)
	if err != nil {
		err = msgp.WrapError(err, "Username")
		return
	}
	// write "favouriteNumber"
	err = en.Append(0xaf, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.FavoriteNumber)
	if err != nil {
		err = msgp.WrapError(err, "FavoriteNumber")
		return
	}
	// write "interests"
	err = en.Append(0xa9, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Interests)))
	if err != nil {
		err = msgp.WrapError(err, "Interests")
		return
	}
	for za0001 := range z.Interests {
		err = en.WriteString(z.Interests[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Interests", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *JsonPerson) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "userName"
	o = append(o, 0x83, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Username)
	// string "favouriteNumber"
	o = append(o, 0xaf, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	o = msgp.AppendInt64(o, z.FavoriteNumber)
	// string "interests"
	o = append(o, 0xa9, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Interests)))
	for za0001 := range z.Interests {
		o = msgp.AppendString(o, z.Interests[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *JsonPerson) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "userName":
			z.Username, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "favouriteNumber":
			z.FavoriteNumber, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FavoriteNumber")
				return
			}
		case "interests":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Interests")
				return
			}
			if cap(z.Interests) >= int(zb0002) {
				z.Interests = (z.Interests)[:zb0002]
			} else {
				z.Interests = make([]string, zb0002)
			}
			for za0001 := range z.Interests {
				z.Interests[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Interests", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *JsonPerson) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.Username) + 16 + msgp.Int64Size + 10 + msgp.ArrayHeaderSize
	for za0001 := range z.Interests {
		s += msgp.StringPrefixSize + len(z.Interests[za0001])
	}
	return
}
